name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: ~

jobs:
  build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test
